# yoiyiyi

1	1	raise the volume
1	1	increase the volume
1	0.5	make the volume louder
1	0.5	make the volume a bit louder
1	0.5	crank the volume
1	.25	pump up the volume
2	1	decrease the volume
2	1	turn the volume down
2	1	turn down the volume
2	1	quiet down
3	1	stop the music
3	1	shut up
4	1	skip this track
4	1	go to the next track
5	1	empty the playlist
5	1	remove all the songs from the playlist
5	1	remove everything from the playlist
